### ISSUE TITLE
Prerequisites for running the command.

### ISSUE THREAD

**Issue by codeangler** [stephencroberts/dotfiles#2]
to execute `sh -c "$(curl -fsSL http://go.stephenroberts.io/dotfiles)" && source ~/.dotfiles/source.sh` some software is required.  

1. `git`

I had errantly thought I could go from new OS install and run the above script and get set up.

**Comment by stephencroberts** [comment]
@codeangler Glad to see you're trying it out! Which OS are you using? `git` is pre-installed on many systems, but the installer should download and install `git` automatically on a supported OS.

**Comment by codeangler** [comment]
@stephencroberts macOS Monterey 12.4.

steps to recreate:

1. open terminal
1. excute `sh -c "$(curl -fsSL http://go.stephenroberts.io/dotfiles)" && source ~/.dotfiles/source.sh`
1. response message


```
casburnett@corp-corp ~ % sh -c "$(curl -fsSL http://go.stephenroberts.io/dotfiles)" && source ~/.dotfiles/source.sh
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.

Installing git
Waiting for git to be installed. Press ENTER to continue.
```

**Comment by stephencroberts** [comment]
@codeangler Did the Mac OS command line tools installer pop up? I think at that point it's supposed to prompt you to install, and dotfiles waits for you to complete that process first. If it's not popping up, something might have changed.

**Comment by codeangler** [comment]
> Mac OS command line tools installer pop up

no.



As I went to install Homebrew separate from this, I've now installed xcode

`xcode-select --install`

and prior to install homebrew, retried this script. 

I'm past the above error.

**Comment by stephencroberts** [comment]
Bah! Sounds like I need to get a VM running to do some testing. Thanks for the feedback!

**Comment by stephencroberts** [comment]
I confirmed this is working as expected on macOS Sonoma, so I'm gonna go ahead and close the issue.
